# Multi-Parameter Models {#multi}

Chapter 3 - To be completed

```{r}
dnorminchi <- function (mu, sig, mu_0, k_0, sig_0, v_0, y) {
  y_mean <- mean(y)
  n <- length(y)
  
  mu_n <- (k_0 * mu_0)/(k_0 + n) + sum(y)/(k_0 + n)
  k_n <- k_0 + n
  sig_n <- sig_0
  v_n <- v_0 + n
  
  return(sig^-1 * (sig^2)^(-(v_n/2 + 1)) * 
           exp((mu-mu_n)^2))
}

dmarginal_mu <- function (mu, mu_0, sig_0, k_0, v_0, y) {
  
  y_mean <- mean(y)
  n <- length(y)
  
  mu_n <- (k_0 * mu_0)/(k_0 + n) + sum(y)/(k_0 + n)
  k_n <- k_0 + n
  v_n <- v_0 + n
  sig_n <- v_0 * sig_0^2 + (n-1)*var(y) + k_0 * n * (y_mean - mu_0)^2 / (k_0 + n)
  sig_n <- sig_n / v_n
  
  print(c(mu_n, k_n, sig_n, v_n))
  
  return(list(mu = (mu - mu_n)^2 * k_n / sig_n^2, df = v_n,
           mu_n = mu_n, k_n = k_n, sig_n = sig_n, v_n = v_n))
}
```

```{r}
# mu <- seq(-10, 10, by=0.1)
# plot(NA, xlim = c(-10, 10), ylim = c(0, 0.5))
# posterior <- dmarginal_mu(mu, 1, 10, 0, 0, c(1,2))
# lines(mu, dt(posterior$mu, posterior$df))
# 
# par(col = "red")
# lines(mu, dmarginal_mu(mu, posterior$mu_n, posterior$sig_n, posterior$k_n, posterior$v_n, 
#                        c(-4,-7,-8,-5,-4,3,2)))
# 
# par(col = "orange")
# lines(mu, dmarginal_mu(mu, 1, 10, 0, 0, c(-4,-7,-8,-5,-4,3,2,2,2,2,2,2,2)))
# 
# par(col = "yellow")
# lines(mu, dmarginal_mu(mu, 1, 10, 0, 0, c(-4,-7,-8,-5,-4,3,2,2,2,2,2,2,2,3,3,3,3,3,3,3)))
```

